#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

RUNBOOK="docs/WIGGUM_RUNBOOK.md"
STATUS_DOC="docs/WIGGUM_AUTOPILOT_STATUS.md"
NOW_UTC="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
HEAD_SHA="$(git rev-parse --short HEAD)"

extract_backlog() {
  awk '
    /## Next Backlog \(Ordered\)/ { in_section=1; next }
    /## Execution Protocol/ { in_section=0 }
    in_section && /^[0-9]+\./ { print }
  ' "$RUNBOOK" | head -n 5
}

BACKLOG_ITEMS="$(extract_backlog)"

cat > "$STATUS_DOC" <<EOF
# WIGGUM Autopilot Status

Generated: $NOW_UTC  
Base commit: \`$HEAD_SHA\`

## Nightly Health
- Build check: passed in workflow run before packet generation.

## Next Recommended Work (From Runbook)
${BACKLOG_ITEMS:-"- No backlog items detected in runbook."}

## Operator Notes
- This file is generated by \`scripts/wiggum-autopilot-packet.sh\`.
- Merge this PR to keep a timestamped execution trail between live coding sessions.
EOF

